language: generic
sudo: required
services:
  - docker
before_install: 
  - docker build -t jeremybjohnson/docker-react -f Dockerfile.dev .

script:
  # -- --coverage exits test suite
  - docker run -e CI=true jeremybjohnson/docker-react npm run test

